### ISSUE TITLE
021_integrate_refresh_token_logic

### ISSUE THREAD

**Issue by tomit4** [cafeDeDevs/pikoshi#21]
# Ticket No: 021

This ticket integrates the logic of using JWT refresh tokens in conjunction with JWT access tokens to establish the refreshing of the access_token after the access_token has expired.

This ticket should start being resolved by investigating the check_auth_context route in the src/pikoshi/routers/auth_context.py file.

**TODO:**

- [x] Within this route, you should see the call to the AuthService.authenticate() method. Note that at the time of this writing, this method only accepts the access_token, add another argument to this function that takes the refresh_token as well.
- [x] Now investigate the AuthService.authenticate() method in the src/pikoshi/services/auth_service.py file. Note how the user is retrieved from the database using the AuthService.get_user_by_access_token() method (investigate these methods and their subsequent methods of your own accord). Note how the method raises a 401 exception if the user or the user.is_active field is not truthy (i.e. either is False or None).
- [x] Add another if check or change the current logic to now check the refresh_token IF the access_token is no longer valid (i.e. does not return a user from the access_token). IF the refresh_token is still good and returns a user by UUID like the access_token does, generate a new access_token using the UUID retrieved from the refresh_token and send it back in the form of a secure http only cookie (see src/pikoshi/utils/auth_cookies.py).
- [x] ELSE IF the refresh token is also bad however, then still send back a 401 exception as both access token and refresh tokens have expired in this case. Make sure to also set the User's is_active field in the DB as False.
- [x] Adjust the lifetimes of the access_token and the refresh_token to be far quicker to test this logic (currently access_token is set at 3600 seconds (1 hour), and the refresh_token is set to 86400 seconds (24 hours), you can see this in the src/pikoshi/utils/auth_cookies.py file). Make absolutely sure your logic for the access_token failing (and being refreshed by the still good refresh_token) works, AS WELL AS making sure you test for the case that both the access_token and refresh_token are no good (you can test this by setting the access_token to a low time like a minute or two, and the refresh_token to a low time that is only a bit longer like 4 or 5 minutes).
- [ ] Adjust the docstrings in all functions that you have adjusted following the current conventions established around in-line documentation (i.e. just try and mimic what is already there in terms of style and explain what additional logic the function is doing).
- [x] Make sure, as always to create a PR(pull request) into dev and assign Brian to the PR. Provide a thorough description of what this PR encompasses in terms of what it contributes to the Pikoshi project.
- [x] NOTE: Do NOT send out a new refresh token, the refresh token should never be generated during the lifecycle of these methods, only the access token is refreshed.

**Comment by tomit4** [comment]
This ticket has been resolved. JWT Refresh Token Logic now works as expected in conjunction with JWT Access Token Logic.
