### ISSUE TITLE
025_feature_forgot_password

### ISSUE THREAD

**Issue by tomit4** [cafeDeDevs/pikoshi#30]
# Ticket No: 025

This ticket creates and implements a feature "Forgot Password". As the name
implies, this feature will allow all users <em>who signed up with email and not
Google Oauth2</em> to retrieve their account credentials and change their
password if they forget their password.

## User Story:

As a User, I want to be able to retrieve my account credentials if I forgot my
password. I should:

- Be presented with a link at the Pikoshi Login Page that says "I Forgot My
  Password"
- This link should lead me to a form where I am required to provide my email
  address.
- Upon filling out the email form, I should be told I have been sent an email.
- Upon checking my email, I should be presented with a link that returns me to
  the Pikoshi application.
- When I click the link in my email, I should be redirected back to the Pikoshi
  Application, which will prompt me to change my password. It should double
  check that I have inputted my password correctly by having a secondary form to
  ensure that I have typed the password correctly into two form inputs.

**TODO:**

- [x] Create a new string field in the User's table called "signed_up_method"
- [x] Adjust the sign up logic for both the oauth2 and the email sign up methods
      that when they sign up with either google or email, that this field
      contains the string "email" or "oauth2" when the user signs up. It should
      either be "email" or "oauth2" depending on how they signed up.
- [x] Establish a link on the frontend from the Login Page that says "I Forgot
      My Password".
- [x] Create a view page that contains a form that asks the user to input their
      email.
- [x] Upon entering their password, this should hit a new `jwt_auth.py` route
      that then does the following:
  - [ ] Checks if the user exists within the User's table, if they don't throw
        back a 400 error response. Otherwise:
  - [ ] Checks if the user signed up with oauth2 via the User Table(if they did,
        throw back a 400 response error with the message that user's who signed
        up via oauth2 cannot reset their password).
  - [ ] Otherwise sends an email to the user provided email that contains a link
        with a unique token. This token should be established very much like the
        signup token logic. (i.e.
        `await redis.set(f"signup_token_for_{token}", user_email, ex=600)`), but
        with different syntax indicating what the user is doing
        (`change_password_token`). Note that a new EmailService method will be
        needed for this, as well as a new email template (see
        services/email_service.py and templates/signup_email.html for references
        and ideas).
- [x] Upon clicking on the link in their email. They should be redirected back
      to a frontend view very much like the Onboarding.tsx view. This should
      initially check to make sure the `change_password_token` is within the
      URL, if it is not, redirect them back home:
  - [x] If the token does exist, then send it to the backend via a new route
        within the routers/jwt_auth.py file that then simply makes sure that
        this token exists within the redis cache. If it does, throw back 200, if
        not , throw an exception with a 401 (see routers/jwt_auth.py check_token
        method for reference).
- [x] Create the frontend logic and html forms that ask the user to input their
      new password and use zod validators to ensure that the inputted passwords
      in both forms are correct and that it follows the zod conventions.
- [ ] Create a new route in the `routers/jwt_auth.py` file that accepts the
      changed password from the user.
- [ ] Within this new route, implement logic that changes the User's password.
      This will interact with the User's table in the DB, so it makes sense for
      this logic to live within the services/user_service.py file, and then can
      have any new methods you establish here to then be called from the new
      route.
- [ ] Upon successful creation of the new password, send back a successful 200
      message to the user, give them time to read it (i.e. await delay(3000)),
      then redirect them back to the login page.
