### ISSUE TITLE
026_integrate_intersection_observer

### ISSUE THREAD

**Issue by tomit4** [cafeDeDevs/pikoshi#33]
# Ticket No: 026

This ticket integrates the use of the
[Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)
in a classic "Infinite Scroll" feature common to many image sharing/social media
platforms.

## User Story

As A User I want to be able to scroll through my Gallery Images and have them
dynamically load as I scroll, creating the illusion that all my images are
loaded. This should create a seamless experience where ideally I should not see
any loading indicators whatsoever (or if I do, they are shown only briefly
before the next set of my images load).

**TODO:**

- [x] Become familiar with the
      [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)
      and simply get the scroll event to be hooked up to it (test via
      console.logs).
- [x] Utilize tutorials and articles to further familiarize yourself with common
      techniques used to create an infinite scroll of gallery images.

- [x] Once familiar, set up the Intersection Observer Implementation in
      `views/Gallery.tsx` file, replacing the "Load More Images" button with
      this Intersection Observer implementation.
- [x] Optimize the pagination/streaming strategy to see if you can get the
      timing of the image loading to be seamless, meaning the user is only aware
      of the images loading if they scroll quickly to the bottom of the page,
      but if they scroll slowly/regular pace, they may never see the loading
      spinners.

**Comment by tomit4** [comment]
This issue is resolved. Intersection Observer API is now integrated with the streaming of thumbnail images in the Gallery view.

**Comment by tomit4** [comment]
This issue is resolved. Intersection Observer API is now integrated with the streaming of thumbnail images in the Gallery view.

**Comment by tomit4** [comment]
This issue is resolved. Intersection Observer API is now integrated with the streaming of thumbnail images in the Gallery view.
