### ISSUE TITLE
config_create_hooks_linters_etc

### ISSUE THREAD

**Issue by tomit4** [cafeDeDevs/pikoshi#36]
# Config: Create Hooks, Linters, Etc.

Lead Developer Story:

As a Lead Developer, I want to have a standard CI/CD pipeline that lints,
formats, and prevents other Developers from pushing their changes without
conforming to the project's formatting conventions. The process should automate
as much as possible, doing as much as possible to not get in the way of
Developer productivity while still enforcing these conventions.

**TODO:**

- [x] Research git hooks and see how you can ensure they are pushed to all new
      developers.
- [x] Research and integrate the use of `rye` commands to help with this
      process. These include `rye fmt`, `rye lint`, and `rye test`.
- [x] Do the same for the frontend with `bun`, this will include more varied
      approaches, like creating bun aliases such as `lint`, `fmt`. This will
      ultimately use other tools like prettier, eslint, tslint, etc.

**Comment by tomit4** [comment]
## Finished:

This PR pulls in quality of life changes for the developer including
autoformatting upon commit as well as database backup utilities.

Additionally a bug :bug: was addressed that was noticed during development. This
bug prevented uploading of initial image upon sign up. FIXED.
